### ISSUE TITLE
Add an option in plugin settings to set the beginning of the week to either Monday or Sunday

### ISSUE THREAD

**Issue by YU000jp** [YU000jp/logseq-plugin-show-weekday-and-week-number#100]
Would it be possible to add an option in config to set the beginning of the week to either Monday or Sunday?

_Originally posted by @samtwalker in https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/discussions/99_

**Comment by samtwalker** [comment]
Thank you for the quick response and work!   I have reloaded and tested, the top calendar (for 2 weeks) is not updating, and when I try to create future days to start the week (choosing Sunday) the week is not being set on that day for the correct week.  i.e. this week is 39th and next week (starting Sunday for me) would be week 40.  Let me know if I am missing something.  

![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/80660962/bb7b9aa3-702b-46a2-b468-6b03bf9aa723)

**Comment by YU000jp** [comment]
@samtwalker 
In that case, set Week number calculation to "US format".
(It was a bug that the mini calendar was not changed when on ISO format.)

**Comment by samtwalker** [comment]
Perfect.  Thank you!
