### ISSUE TITLE
Click to a future date

### ISSUE THREAD

**Issue by minxu-nyc** [YU000jp/logseq-plugin-show-weekday-and-week-number#102]
This plugin works well for moving between journal entries of today and the past by just clicking on the mini calendar. However, it does not move to the journal entry or create a new journal entry when clicking on a future date. Is this the expected behavior? It would be very useful to move to the journal entry or create a new entry if none exists when a future date is clicked. 

Thanks!

M

**Comment by YU000jp** [comment]
OK.

I released.

**Comment by minxu-nyc** [comment]
Thanks! This is wonderful. By the way, I noticed the layout for the mini calendar has changed to two rows of fixed 14 days. Can a "smarter" version of the mini calendar be implemented so that the current week is placed on the top or bottom row to give a similar number of days before and after "Today" in the view?

M

**Comment by YU000jp** [comment]
@minxu-nyc 
I didn't quite grasp the idea mentioned in the previous message about the smarter version of the mini calendar. Could you please explain it again?

**Comment by minxu-nyc** [comment]
Take 9/30/23 (today) as an example. The default mini-calendar will place the current week at the bottom row. In the view, the number of days before and after today are 12 and 1, respectively. This is not desirable. A better placement will keep the current week in the top row instead. This would provide 5 and 8 days before and after today. The idea is to provide a more balanced number of days before and after today in the view.

**Comment by YU000jp** [comment]
@minxu-nyc 
I see.  I choose a realistic method. If the date is two days before the last day of the week, the following line will display.
One or three lines may be preferable. but, the design is not good. I may improve it so that it can be updated by scrolling someday when I have time.

**Comment by YU000jp** [comment]
Implemented the function to switch rows.
