### ISSUE TITLE
bug report - weekly journal.

### ISSUE THREAD

**Issue by gomtinQQ** [YU000jp/logseq-plugin-show-weekday-and-week-number#111]
Hi, 

i'm using "this week section : top" option.
I've some repeat-thing bug for weekly journal.

my weekly journal create like
- empty block
- tags: ..
- this week

When i go to 2023-W43 page at first time, then create this week block well.
but, go to 2023-W43 page again, then re-create this week block, every time repeat to create like below :

my weekly journal create like
- empty block
- tags: ..
- this week
- empty block
- tags: ..
- this week
- empty block
- tags: ..
- this week
...

If I delete empty block, then I work well... maybe code check first block.
but, plugin create new weekly journal with first empty block, I don't know why..

**Comment by YU000jp** [comment]
I was able to reproduce it. I will check it a bit more.
