### ISSUE TITLE
Calendar not being responsive to journal width

### ISSUE THREAD

**Issue by senntore** [YU000jp/logseq-plugin-show-weekday-and-week-number#113]
I use auto tiling, so most often the logseq window uses half of the montior & the calendar above the journal looks fine.
But when I open right sidebar, the calendar doesn't scale down to fit the new width of the journal & obstruct the journal title.
Screenshot with right side bar open:
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/58325574/18d8a33b-b21b-40f6-b5b2-bed9a6f76dff)

Plugin version: 1.39.5
Logseq: 0.9.19
OS: Pop!_OS

**Comment by senntore** [comment]
I can disable the calendar but I really want them as I can access the monthly journal, like **Oct** on the right of calendar here.
Maybe adding an option in the settings for monthly journal to appear next to the journal title can also helpful.

**Comment by YU000jp** [comment]
It's a bug. I released new version.
It's also affected by themes, so if you find any problems, please let me know.

**Comment by senntore** [comment]
@YU000jp Thank you, it's working much better now.

**Comment by senntore** [comment]
By the way would it also be possible to link monthly journals alongside weekly ones next to journal title
In here:
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/58325574/8bca5335-49e5-4490-a76b-a05d7e34bdb5)

**Comment by YU000jp** [comment]
I see. It is possible. How should I express that link title? I can't find a suitable choice.😅
I will release at a next version.

**Comment by YU000jp** [comment]
@senntore I released a new version. The default is false, so set it to true.

plugin settings: 
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/9fa8c23d-9664-43d9-8979-fb392bb48406)

**Comment by senntore** [comment]
Thank you!! It's working just like how I wanted it to be.
