### ISSUE TITLE
Feature Embeding for Weekly Journal

### ISSUE THREAD

**Issue by nrobran** [YU000jp/logseq-plugin-show-weekday-and-week-number#119]
It would be really helpful to have the possibility to use the embedding feature for the weekly journal. 

Like this:

```md
- {{embed [[Oct 23rd, 2023]]}}
- {{embed [[Oct 24rd, 2023]]}}
- {{embed [[Oct 25rd, 2023]]}}
```

**Comment by YU000jp** [comment]
I see. I'm thinking of adding a option like this to the "This Week" corner. Does it match your idea?
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/7a58d070-55c6-4557-95d7-7c9b67aea2c2)

**Comment by nrobran** [comment]
Yes that is exactly what i thought of

**Comment by YU000jp** [comment]
OK. I add as an option.

**Comment by YU000jp** [comment]
I released a new version. Try it.

**Comment by nrobran** [comment]
I already did it looks awesome thank you for your fast implementation and keep up the good work.

**Comment by YU000jp** [comment]
I'll write this just in case.
It seems to count as 2 references in "Linked References". They overlap. I can't think of a solution at the moment.

**Comment by YU000jp** [comment]
@nrobran 
In connection with this. With "Linked References", one reference and one date link counts as two. Added a setting to disable that date link. (By default, this setting is off.)

**Comment by nrobran** [comment]
I see why you did this and it works good. I thought about the possibility to have ether the Link or the embedding in the same place. This why you would just have to decide if you want to turn embedding on or off. But you know best what configs you want and need for you Plugin I am happy regardles of what you do here.

![grafik](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/39692541/5b4ac8b7-7dd4-4fd2-b389-2de3bf080989)

**Comment by YU000jp** [comment]
Yes. Sometimes it is difficult to achieve both.
