### ISSUE TITLE
Top icons of other plugins seemed unclickable

### ISSUE THREAD

**Issue by yoghurtdewdew** [YU000jp/logseq-plugin-show-weekday-and-week-number#124]
![🗯️logseq 点不了插件图标](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/89001eac-76bd-4d17-a2cb-a949a3c17d07)

Hello! I love this plugin so much!
Recently I found that the top icons of other plugins were hard to click, as the gif showed.

Hope this could be fixed soon :)

Thanks again for your great work for this amazing and lovely plugin 🥰

**Comment by YU000jp** [comment]
@yoghurtdewdew 
It doesn't reproduce in my environment. Will turning this plugin on or off make a difference?

**Comment by yoghurtdewdew** [comment]
Yes, turn on & off make it different. And I usually use ⌘+ ⌘- to resize the window, and that is possible to make a difference, I think.

**Comment by YU000jp** [comment]
I haven't improved the toolbar buttons for a long time. So there must be an issue with the toolbar's HTML code, caused by one of the plugins. Or this may be caused by the version update of Logseq. Try turning off all other plugins and trying it alone.

**Comment by yoghurtdewdew** [comment]
Hi, I haven't tried close all the plugins, since this plugin doesn't include the toolbar buttons to test this issue. Luckily, I found the icons seemed normal, it may be fixed by the version update of logseq, or may be caused by the display screen as I had one external monitor at that time I tested.
