### ISSUE TITLE
Option to hide days from previous week in mini calendar

### ISSUE THREAD

**Issue by senntore** [YU000jp/logseq-plugin-show-weekday-and-week-number#127]
I think it would make the calendar more compact & help in focusing more on writing the journal.
This is what it could look like, 
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/58325574/507278bc-eb6f-4e76-a4b8-d82400033d32)

**Comment by YU000jp** [comment]
It is not designed to be displayed in just one line. That option used to exist, but we removed it in favor of built-in functionality. It will switch to the upper row from mid-week.
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/5c6444cb-f092-4ba3-9bf0-22581f445447)
I also think it should be more compact. It is currently being created.
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/d379f8db-3d39-41c1-a269-ad30ced51d9b)

**Comment by YU000jp** [comment]
I Added `Show boundaries on bottom` to plugin settings and, release a new version. Display the mini calendar at the bottom instead of the top. Starting a design change can be a lot of work, so I'll avoid it for now.

**Comment by senntore** [comment]
Yeah that's completely understandable. I like the changes made in last few updates.
