### ISSUE TITLE
Show Lunar Calendar date

### ISSUE THREAD

**Issue by yoghurtdewdew** [YU000jp/logseq-plugin-show-weekday-and-week-number#129]
When making plans and travel arrangements, it may be necessary to consider lunar related birthdays, holidays, and festivals.

**Comment by YU000jp** [comment]
It is possible to replace the displayed date and make it mouse over.
If it is common to use the lunar calendar as a calendar in China, I would like to support that, but I doubt whether it useful by this plugin. If a monthly calendar like "Journal Calendar plugin" or "days plugin" is more suitable, I think it would be better to implement it with that type.

**Comment by yoghurtdewdew** [comment]
Yes, Lunar calendar is used at the same time in China. Hover to show is also a good idea I think.
What I'm thinking is that the lunar date can be displayed next to the day of the monthday & weekday as an aid to identification, but the lunar calendar would not show without the original and commonly used date. Hope it could show two dates at the same time. I put pics to be examples.

Apple calendar:

<img width="707" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/764fb1cf-8272-490c-912f-dbb3fbc51173">

My thought:

<img width="610" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/2a2c615d-8db7-4212-9ace-8dcd6900a592">

Current display:

<img width="591" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/ffe80867-ac96-4b6e-861a-98c8c0dce6b9">

**Comment by YU000jp** [comment]
Thanks to that image, I know how you want it to look. I haven't tried it yet, but I discovered a library that helps make it happen, so it's likely possible. https://github.com/6tail/lunar-typescript?tab=readme-ov-file

**Comment by YU000jp** [comment]
@yoghurtdewdew 
I've included the sample in a new version and released it. Look for holidays on the calendar.

TODO
1. Journal Boundaries
   - [ ] support lunar calendar https://6tail.cn/calendar/api.html#lunar.ymd.html
   - [ ] get holidays https://6tail.cn/calendar/api.html#holiday-util.ymd.html
1. Behind journal title
   - [ ] month and day https://6tail.cn/calendar/api.html#lunar.string.html
1. Plugin settings
   - [ ] Toggle

Features: for Chinese people

**Comment by YU000jp** [comment]
@yoghurtdewdew 
I included this change in a new version and released it. Please let me know if any changes still need to be made.

**Comment by yoghurtdewdew** [comment]
Wow! It just worked so nice and beautiful! You are so creative!

<img width="900" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/dc5e3538-eaf7-47c2-aa59-e62ebb45de8f">

<img width="872" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/549e97a5-4e9c-4bc3-8c35-f98f22661dc5">

I still have some requests. I wonder if there could show Lunar Calendar date both on the first line and second line? Now it only shows on the second line.

And if there will be a button to show & hide holiday so as to quickly get to know the Lunar date? Now it shows seven "春节" on W07 and not easy to know each Lunar date.

**Comment by YU000jp** [comment]
- [ ] Display the lunar calendar on both sides instead of one
- [ ] Prioritize the lunar calendar over holidays

**Comment by yoghurtdewdew** [comment]
<img width="480" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/ff1da556-acc1-4283-a968-a9c4d299a764">
Hi I found after updates of "Prioritize the lunar calendar over holidays" there will show no holidays on the calendar as the lunar dates are one-to-one correspondence. 🤔

**Comment by YU000jp** [comment]
The holiday part is marked with a marker. If you hover the mouse over it, you will see a detailed of the day.
