### ISSUE TITLE
Feature request: show which dates have an existing journal entry

### ISSUE THREAD

**Issue by hmijail** [YU000jp/logseq-plugin-show-weekday-and-week-number#130]
Would be great it dates with a journal had a dot or some indicator, just like the ["Journals Calendar"](https://github.com/xyhp915/logseq-journals-calendar) plugin does.

**Comment by YU000jp** [comment]
Is it okay to just know if the page exists? It's not impossible. But it will require processing more frequently than the plugin, in this plugin. After verifying the load level, add it to the plugin settings.

**Comment by hmijail** [comment]
Personally, I purge the empty pages from time to time, so I guess checking for page existence would be enough... though of course it'd be best if it could check whether pages actually contain something.

**Comment by hmijail** [comment]
(I guess this is yet another example of why the existence of empty journal pages is a problem that should be fixed in Logseq!)

**Comment by YU000jp** [comment]
I included this change in a new version and released it. Please let me know if any changes still need to be made.

**Comment by hmijail** [comment]
Finally I got the update. Looks great, thank you!

**Comment by YU000jp** [comment]
> (I guess this is yet another example of why the existence of empty journal pages is a problem that should be fixed in Logseq!)

@hmijail
It might be possible to create a plugin that checks for a week's worth of journals that are empty. Checking the contents of all files requires a processing load, but I don't think it's a problem if it's about 7 pages. The check process is based on the time difference. To check them when a plugin is loaded or when a journal is created. And delete it. I would like to know the contents of the file in that case. I think it probably looks like "` - `". ( I don't have this issue, so I don't know the details. )

**Comment by hmijail** [comment]
I was going to answer that actually it might be easiest to just delete the previous day's journal if it's empty. But turns out that that link proposes just that.

Unfortunately looks like 75 votes and 1+ year of discussion across 2 forums is not enough.
