### ISSUE TITLE
The border in the top row of minicalendar gets overlaid

### ISSUE THREAD

**Issue by fmontagut** [YU000jp/logseq-plugin-show-weekday-and-week-number#136]
With the new version 1.53.1, the holidays shown in the mini-calendar are shown with  an outline instead of with different background. 

The outline is either too big or the padding is too wide. If there are holidays in the upper row of the minicalendar, part of the outline gets overlaid, see the graphic:
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/8792652/83abade7-d16f-4a75-b9ee-a87fd250cf1a)

**Comment by YU000jp** [comment]
It is a design change that is intended to be temporary. The design may seem odd.
The reason for this change was that there were cases where the text color and background color did not match. I'm going to express it in a different way. But I'm still out of ideas.
