### ISSUE TITLE
Mobile compatibility 

### ISSUE THREAD

**Issue by tanhoaian01** [YU000jp/logseq-plugin-show-weekday-and-week-number#139]
Hello, I would like to know if it's possible to show week number in the Logseq Android app? [Awesome Content plugin](https://github.com/yoyurec/logseq-awesome-content) has a CSS code for the mobile app and I wonder if this plugin can also have that?

**Comment by YU000jp** [comment]
This plugin does not provide the same functionality, but if you just want to display it, the following discussion provides some information:
https://discuss.logseq.com/t/show-week-day-and-week-number/12685/1
It uses Javascript (custom.js) instead of CSS.

**Comment by tanhoaian01** [comment]
Thank you for the link. I will take a look.
