### ISSUE TITLE
Feature Request: Add Quarterly Hierarchy 

### ISSUE THREAD

**Issue by HeatDeathOfUniverse** [YU000jp/logseq-plugin-show-weekday-and-week-number#140]
Is it possible to add a quarterly hierarchy in front of the month?
Planning on a yearly basis is a bit too long, it would be easier and more flexible to plan on a quarterly basis.

**Comment by YU000jp** [comment]
Certainly, including it in the hierarchy has the advantage of allowing to check them all at once. Good. Other users have similar isue.

I don't know what to call each quarter. Is it something like "1Q"?

**Even if this option were added, it would not be applicable to all existing monthly pages, so you would have to rename them manually.

**Comment by HeatDeathOfUniverse** [comment]
> Certainly, including it in the hierarchy has the advantage of allowing to check them all at once. Good. Other users have similar isue.
> 
> I don't know what to call each quarter. Is it something like "1Q"?
> 
> **Even if this option were added, it would not be applicable to all existing old monthly pages, so user would have to rename them manually.

Maybe '2024-Q1' is enough, perhaps we should not add another hierarch , but instead, just add an additional type like '2024-W20', and place entries like '2024/01' under '2024-Q1'.

**Comment by YU000jp** [comment]
By the way, would you like to have a system where "Quarterly Journal" is automatically generated like "Weekly Journal"?

My plan is to give users the option to choose between the current "2024-W20" or new "2024/Q1/W20", "2024/W20". In that case it would be a breaking change.
There should also be an option to specify it in the page tag. ("2024-Q1","2024/Q1")

Users have differing opinions on whether to use "-" or "/".

**Comment by YU000jp** [comment]
For compatibility, I will also include a program to rename the Weekly pages for 2023 or 2024.

**Comment by HeatDeathOfUniverse** [comment]
> By the way, would you like to have a system where "Quarterly Journal" is automatically generated like "Weekly Journal"?
> 
> My plan is to give users the option to choose between the current "2024-W20" or new "2024/Q1/W20", "2024/W20". In that case it would be a breaking change.
> There should also be an option to specify it in the page tag. ("2024-Q1","2024/Q1")
> 
> Users have differing opinions on whether to use "-" or "/".

Yes, "Quarterly Journal" is what I want.
As for the different opinions of users, I initially thought that "2024/Q1/January /W1" was too long, and I wanted to keep the system as simple as possible. But since the format of "2024/01" has been used in the month, I think it is a good choice to keep consistency. It can give patients with obsessive-compulsive disorder a sense of pleasure, and can also make good use of the hierarchical function of Logseq for rapid navigation. Maybe it is a better choice to use "/"uniformly.

**Comment by HeatDeathOfUniverse** [comment]
> For compatibility, I will also include a program to rename the Weekly pages for 2023 or 2024.

I can really see how much work you have on your plate right now.

**Comment by YU000jp** [comment]
I released v1.54.0.
Could you please try it?

In the plugin settings, change the option for week number format and run the toggle for old page names.
WeeklyJournal will generate a page like 2024/Q1/W01.
Certain templates will be applied when accessing 2024/Q1 or 2024/05.

**Comment by HeatDeathOfUniverse** [comment]
It's working normally, but now the hierarchy displayed in the "Year" page under Hierarch is a bit messy. Perhaps you could add a configuration option to achieve a format like "Year/qqq/MMM/Www"? It's good enough already, this is just to satisfy some of my obsessive-compulsive tendencies.
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/53603499/6a1dd14e-7697-45c6-90b7-d4546987173a)

**Comment by YU000jp** [comment]
It's difficult because there are no rules for categorizing by month. This is particularly inconvenient when changing years. If quarter, It can be neatly divided into quarters.

**Comment by HeatDeathOfUniverse** [comment]
I'm not quite clear, in the previous version didn't each week also have a month label? What I mean is not to divide by month, but still divide by year, yet this week can be put into a certain month according to a certain rule. This way, when there is a cross-month situation, this rule can be used to put the cross-month week into a month.

The rule could be the month of the first day of the week. For example, suppose W21 spans from May to June, then W21 would be like this: "2024/Q2/05/W21".

This rule could also be that the week is counted in the month where more days fall. So if W21 has three days in May but four days in June, then its hierarchy would be "2024/Q2/06/W21".

The benefit of doing this is that you get a very clear hierarchy. You can quickly switch between different perspectives using this hierarchy.
It might be a bit troublesome to implement, but a simpler option could be to replace the month with "2024-05", so it no longer appears in my hierarchy.

**Comment by YU000jp** [comment]
No, it looks like that's a rule you made. I can't take responsibility for that.

**Comment by HeatDeathOfUniverse** [comment]
Yes, so I've said before that the current features are enough, and that's just my idea.
