### ISSUE TITLE
The mini-calendar at the bottom reappears after disabling

### ISSUE THREAD

**Issue by kelszo** [YU000jp/logseq-plugin-show-weekday-and-week-number#148]
Despite disabling the mini-calendar in the settings it reappears.

Steps to reproduce:
1. Disable the mini-calendar under `2. Journal boundaries (mini calendar) > Enable feature`
2. Be on the journal page
3. Switch to another page (for example by using the recents pages tab)
4. Switch back to the journal
5. The mini-calendar is on the bottom again.

**Comment by YU000jp** [comment]
It is a bug. There are three toggles, each working independently of the other by mistake. I will fix it later. For now, please turn off the toggle for all three.

**Comment by YU000jp** [comment]
I released a new version. Please update.

**Comment by kelszo** [comment]
It is fixed, thank you!
