### ISSUE TITLE
Monthly calendar sticks out of the sidebar

### ISSUE THREAD

**Issue by laughedelic** [YU000jp/logseq-plugin-show-weekday-and-week-number#153]
Hi! Thank you for the great plugin! There's a lot of useful functionality, but I'm experiencing some visual glitches. 

One example is that the monthly calendar doesn't resize together with the sidebar.  So if I make the sidebar narrower (which is useful on a smaller laptop screen), the calendar sticks out:

<img width="323" alt="Screenshot 2024-11-13 at 02 14 07" src="https://github.com/user-attachments/assets/a2f2c522-d035-4b0c-b8dd-a796a50c25f6">

Would it be possible to scale the calendar overall size to fit the panel? Another approach could be to hide the calendar when the panel is too small. Or to optionally have it behind a pop-up button (similar to https://github.com/xyhp915/logseq-journals-calendar)

**Comment by YU000jp** [comment]
Reduced the size of the monthly calendar to correspond to the smallest size of the left sidebar and applied that change. Please update.
