### ISSUE TITLE
Feature request: Display of the week number according to ISO standard 8601

### ISSUE THREAD

**Issue by garderobier** [YU000jp/logseq-plugin-show-weekday-and-week-number#34]
It would be nice to support to display week numbers according the ISO standard 8601.
And example would be 2023-W22.

**Comment by YU000jp** [comment]
I see. So, for example, instead of having the week number of January 1, 2024 as `Week 53`, it would be more appropriate to represent it as `2023-W53`, as you mentioned.

**Comment by YU000jp** [comment]
Preview
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/a277b755-91cb-4876-8d68-6d495e08e66f)
