### ISSUE TITLE
Something is displaying above boundaries

### ISSUE THREAD

**Issue by plskz** [YU000jp/logseq-plugin-show-weekday-and-week-number#48]
## Steps to Reproduce

1. Go to Whiteboards
2. now this will show

    <img width="362" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/57343545/02b04114-ea65-46f2-9961-483a3b5a5b2f">

1. Go to journals or any pages (non-journals)

    `journals`    

    <img width="1063" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/57343545/1865ae29-3d13-4805-9caf-f5c438449ef2">

    `today`

    <img width="1063" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/57343545/d1003bdd-24ad-42b1-b61c-60f5c22bc7ae">
    
    `pages`

    <img width="1063" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/57343545/171f6f9d-0c64-4042-93e2-ddb221dd4228">

## Expected Behavior

- It should not display

## Temporary fix

- Reload Logseq (⌘ + r) 
or 
- Quit and Open it again.

## Additional info

- Operating System: macOS
- Logseq Version: 0.9.9 (0.9.9) (latest)
- Plugin Version: v1.16.0 (latest)

**Comment by YU000jp** [comment]
I was able to reproduce the bug as you described. Thank you for providing a clear issue. It will be fixed in the next release.🌞

**Comment by plskz** [comment]
@YU000jp thank you!
</br>
<div align="center">

![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/57343545/eb7728e3-6949-4b14-8e94-1252c6902a58)

</div>
