### ISSUE TITLE
Custom day range for boundaries

### ISSUE THREAD

**Issue by sourcebert** [YU000jp/logseq-plugin-show-weekday-and-week-number#58]
It would be great to have the ability to customize the fixed value of 10 days in the settings and/or have an option that aligns the time span with the current week (based on the global week start setting).

BTW Nice plugin! Thank you for your effort :+1:

**Comment by YU000jp** [comment]
I will release new version.

### Add to plugin settings
- The boundaries 2 week mode (only journals)
  -  default: `false`
- The boundaries custom day range: before today (Excludes 2 week mode)
- The boundaries custom day range: after today (Excludes 2 week mode)

**Comment by YU000jp** [comment]
Regarding the upcoming two-week mode that I will release, there is still room for improvement in terms of design, but for now, I will include it in the release.
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/67145495-7359-44b8-8f73-332eedcb8667)

**Comment by sourcebert** [comment]
Thank you so much for implementing the feature!

I have a small suggestion: Would it be possible to allow setting the custom day range for 'before today' to 3 days instead of the minimum value of 5? This would help cover a full week in total. It would be really helpful!
Once again, thank you for your efforts!

**Comment by YU000jp** [comment]
OK!
