### ISSUE TITLE
custom day range for 'before today' to 3 days instead of the minimum value of 5

### ISSUE THREAD

**Issue by YU000jp** [YU000jp/logseq-plugin-show-weekday-and-week-number#60]
I have a small suggestion: Would it be possible to allow setting the custom day range for 'before today' to 3 days instead of the minimum value of 5? This would help cover a full week in total. It would be really helpful!
Once again, thank you for your efforts!

_Originally posted by @sourcebert in https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/issues/58#issuecomment-1616804078_

**Comment by sourcebert** [comment]
Thank you for adding this! 👍

**Comment by YU000jp** [comment]
@sourcebert
With the new update, now be sure to cover the entire week. (Show a two-layer calendar starting from the first day of the week) 🫡

**Comment by sourcebert** [comment]
Wow 😲 Good work! Thank you so much! 🙏🏼
