### ISSUE TITLE
Displayed strange

### ISSUE THREAD

**Issue by yoghurtdewdew** [YU000jp/logseq-plugin-show-weekday-and-week-number#61]
<img width="1020" alt="image" src="https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/63794438/50f16cab-2266-4e0b-b7a2-888105243f1a">
The display is strange, it should have been displayed to the left.
BTW, I'm using the format of "YYYY-MM-DD EEE" of journal title before. Thanks for fixing work on #54 so I can see the fantastic plugin worked.

**Comment by YU000jp** [comment]
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/27cee4ea-4688-4727-8621-c45cef942cea)

###  plugin settings
 
 - Alignment of journal page title
   - select `left`

**Comment by yoghurtdewdew** [comment]
Thanks so much!
