### ISSUE TITLE
[FEATURE REQUEST] Only show week number

### ISSUE THREAD

**Issue by DutchPete** [YU000jp/logseq-plugin-show-weekday-and-week-number#84]
The way it is set up right now is like this:

![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/10794265/2c408355-ec9d-43ea-b268-198c1193f229)

Since the year is already shown in the page title, there is no need to show it again by the extension; I would just like to see the W33 part.

Would it be possible to include this as a toggle?

**Comment by YU000jp** [comment]
The notation follows the rules based on ISO 8601. The reason for the necessity of distinguishing years is that the first week of a year might be included in the last week of the preceding year. If this is omitted, the notation becomes W53 for the first week of that year. These are the reasons for such a setup. Nevertheless, would it be want to include additional options for omitting the ISO 8601 notation?

**Comment by DutchPete** [comment]
I am happy with the ISO 8601 rules, I use them for dates in all my apps.
If it is not possible to leave off the year via the plug-in, do you happen to know if it is possible via CSS?

**Comment by YU000jp** [comment]
The previous reply was a mistake. Only in the case of W53 can the processing be adjusted to ISO8601.  The config item will be added in the next release.

**Comment by YU000jp** [comment]
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/fe440100-4f12-4deb-a484-81eafdee2ccf)
I released.

**Comment by DutchPete** [comment]
Many thanks for the quick response. 👍
