### ISSUE TITLE
how to remove month, year of tags from weekly journal page?

### ISSUE THREAD

**Issue by gomtinQQ** [YU000jp/logseq-plugin-show-weekday-and-week-number#93]
hi, thank you for previous yearly page template!!

I'm looking for option to not added remove month, year of tags for weekly journal page.

maybe weekly journal template option is possible to only add.. right?

is there way to toggle on/off to add [[2023-10]], [[2023]] on tags?
may not, would you add this option to off option?

year page is very nice for me, 
but weekly journals page tags [[2023-10]], [[2023]] is little bit distrub when I looking for real goal and real note on [[2023]] page.
because 52 tags would be there. and 52 * 2 lines would be show up.

so, I need some way to skip add month, year - [[2023-10]], [[2023]] for weekly journal page tags

when created 2023-W41 journal, show tags like this
tags:: 2023-10,2023,2023-W40,2023-W42,

but, some option are working and then show tags like this
to-be: tags:: 2023-W40, 2023-W42

I hope you review it positively.

**Comment by YU000jp** [comment]
OK. I will release at next version.

**Comment by YU000jp** [comment]
![issue](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/9013e5bd-b590-405b-a06d-0d3f8e5c009c)

Add a setting.
Select `yyyy-Ww, yyyy-Ww`

**Comment by gomtinQQ** [comment]
very nice for me. happy 👍
