### ISSUE TITLE
suggestion of weekly journal blank line option.

### ISSUE THREAD

**Issue by gomtinQQ** [YU000jp/logseq-plugin-show-weekday-and-week-number#96]
thank you for options 👍 

another suggestion of weekly journal option is about blank lines before THIS WEEK block.

![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/17059492/269cf210-0af8-4ea3-be4c-ee3bdc422410)

this is little bit interrupt to batch task for day by day.

If write down task list then hide this week block in laptop.
and then batching task is hard with small monitor.
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/17059492/5a9f44f7-ae2a-4cae-85e3-df17ec5c3210)

but, if this week is place on top and blank line is place on bottom like that.
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/17059492/f87aa14f-bec5-438b-b2bf-54a029988cd2)

write down task list 
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/17059492/8c36bafb-30c4-4f32-b5c4-e59216b19004)

and then batch task list on day by day like this with laptop which has small height monitor.
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/17059492/3680f181-8b34-457c-8967-c54b9e697261)

also this way is easy to drag and drop to batch task on day.
moving task by keyboard is also easier.

because of logseq block indeptation policy. 

anyway, I'm need some option to adding blank line on bottom. it would be nice to me. 

thank you for your effort.

**Comment by YU000jp** [comment]
It's the right showcase. I created it with the idea that "This Week" sections would be nested.

I think there should be an option to put that section at the top instead of at the bottom. I will to include it in the next release for your request. 🆗

**Comment by YU000jp** [comment]
![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/5a1278b5-11b4-4109-bb43-44647394ffbc)

I released a new version. Added a setting to plugin settings.

**Comment by gomtinQQ** [comment]
thank you 👍
